###
POST http://localhost:5000/question/create
Content-Type: application/json 

{ 
  "description": "This is a question",
  "tag": "test",
  "point": 1,
  "options": ["ABC", "DEF", "GHI"]
}

###
GET http://localhost:5000/question/view