###
POST http://localhost:5000/question/create
Content-Type: application/json 

{ 
  "description": "This is a question",
  "tag": "test",
  "point": 1,
  "options": ["ABC", "DEF", "GHI"]
}

###
GET http://localhost:5000/question/view

###
GET https://fathomless-gorge-46351.herokuapp.com/question/view

###
POST https://fathomless-gorge-46351.herokuapp.com/question/create
Content-Type: application/json 

{ 
  "description": "This is a question from heroku",
  "tag": "test",
  "point": 1,
  "options": ["ABC", "DEF", "GHI"]
}
###